config/routes.rb
Rails.application.routes.draw do
  root 'orders#new'

  post 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  post 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"

  resources :products
  resources :orders

  get 'confirmation' => 'pages#confirmation'

  get '*path' => 'orders#new'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
# frozen_string_literal: true

class Customer < ApplicationRecord
  has_many :orders

  validates_presence_of :name, :email
end

app/models/line_item.rb
# frozen_string_literal: true

class LineItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
  accepts_nested_attributes_for :product

  def subtotal
    product.price * quantity
  end
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :line_items, inverse_of: :order, dependent: :destroy
  has_many :products, through: :line_items
  belongs_to :customer
  accepts_nested_attributes_for :line_items, :customer, :products

  validates_presence_of :line_items, :delivery_method

  enum status: {
    submitted: 'submitted',
    paid: 'paid',
    completed: 'completed'
  }

  enum delivery_method: {
    pickup: 'pickup',
    delivery: 'delivery'
  }

  def total_price
    line_items.map(&:subtotal).reduce(:+)
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  has_many :line_items
  has_many :orders, through: :line_items

  validates_presence_of :price, :name, :category
  validates :name, uniqueness: { case_sensitive: false }

  enum category: {
    bread: 'bread',
    pastry: 'pastry',
    cake: 'cake',
    biscuits_and_cookies: 'biscuits & cookies',
    pantry: 'pantry'
  }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/orders_controller.rb
# frozen_string_literal: true

class OrdersController < ApplicationController
  before_action :set_order, only: %i[edit update]
  http_basic_authenticate_with name: 'todo', password: 'changeme', except: %i[new create]

  def index
    @orders = Order.all
  end

  def new
    @order = Order.new
    @products = Product.all
    @order.build_customer
    @order.products.build
  end

  def create
    @order = Order.new(order_params.slice(:note, :delivery_method))
    @order.build_customer(order_params[:customer_attributes])
    @order.line_items.build(line_item_params)
    @order.save!
    redirect_to '/confirmation'
  end

  def edit; end

  def update
    # TODO: Fix params
    @order.update(order_params)
    redirect_to orders_path
  end

  private

  def order_params
    params.require(:order)
          .permit(
            :note, :delivery_method,
            customer_attributes: %i[address email name telephone],
            products_attributes: [:id, line_items: [:quantity]]
          )
  end

  def set_order
    @order = Order.find(params[:id])
  end

  def line_item_attributes
    order_params[:products_attributes].values.reject do |product_attributes|
      product_attributes['line_items']['quantity'].blank?
    end.pluck(:id, :line_items)
  end

  def line_item_params
    line_item_attributes.map do |attrs|
      { product_id: attrs.first, quantity: attrs.last[:quantity] }
    end
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def confirmation
    render
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  before_action :set_product, only: %i[edit update destroy]
  http_basic_authenticate_with name: 'todo', password: 'changeme'

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    redirect_to products_path
  end

  def edit; end

  def update
    @product.update(product_params)
    redirect_to products_path
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :description, :category)
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/orders_helper.rb
# frozen_string_literal: true

module OrdersHelper
  def delivery_methods
    Order.delivery_methods.keys
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Black Isle Bakery webshop
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/orders/_form.html.haml
= form_with model: @order do |f|

  = f.fields_for :customer do |f|
    = f.label :name
    = f.text_field :name, required: true, autofocus: true, placeholder: 'Required'

    = f.label :email
    = f.email_field :email, required: true, placeholder: 'Required'

    = f.label :telephone
    = f.telephone_field :telephone

    = f.label :address
    = f.text_area :address, placeholder: 'Required for deliveries'

  %br

  - delivery_methods.each do |delivery_method|
    = f.radio_button :delivery_method, delivery_method, required: true
    = f.label delivery_method.to_sym

  %br

  - @products.each do |product|
    = f.fields_for :products do |p|
      = p.fields_for :line_items do |line_item_form|
        = p.label :name, product.name
        = p.hidden_field :id, value: product.id
        = line_item_form.number_field :quantity
        %br

  = f.label :note, 'Special instructions? Add them here:'
  = f.text_area :note

  %br

  = f.submit

app/views/orders/edit.html.haml
= render 'form'

app/views/orders/index.html.haml
%h2 Orders
- @orders.each do |order|
  %p
    Customer:
    = order.customer.name
    %br
    - if order.delivery?
      Address:
      = order.customer.address
    - else
      PICKUP
    %br
    Telephone number:
    = order.customer.telephone
    %br
    Email address:
    = order.customer.email
    %br
    Order:
    %ul
      - order.line_items.each do |line_item|
        %li
          #{line_item.quantity} x #{line_item.product.name}
    Total:
    = number_to_currency(order.total_price, unit: '€')
    %br
    %br
    Note:
    = order.note
    = button_to "Edit", edit_order_path(order), method: :get
    %br
    %br

app/views/orders/new.html.haml
= render 'form'

app/views/pages/confirmation.html.haml
Thanks for your order

app/views/products/_form.html.haml
= form_with model: @product do |f|
  %p
    = f.label :name
    %br
      = f.text_field :name, required: true, autofocus: true
    %p
      = f.label :price
      %br
        = f.number_field :price, step: 0.5, required: true
    %p
      = f.label :description
      %br
        = f.text_field :description
    %p
    = f.submit

app/views/products/edit.html.haml
= render 'form'

app/views/products/index.html.haml
%h2 Products
- @products.each do |product|
  %p
    %strong= product.name
    %br
    Description: #{product.description}
    %br
    Category: #{product.category}
    %br
    Price: #{number_to_currency(product.price, unit: '€')}
    = button_to "Edit", edit_product_path(product), method: :get
    = button_to "Delete", product_path(product), method: :delete, data: {confirm: "Are you sure?"}
    %br
= button_to "New product", new_product_path, method: :get

app/views/products/new.html.haml
= render 'form'